

const hpCharacters = [
  
  {
    _id: '1',
    name: 'iPhone 12 Pro "BLUE" 256GB',
    image: 'images/Apple/iphoneblue.jpg',
    description:
      'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
    brand: 'Apple',
    category: 'Electronics',
    price: 1000.00,
    countInStock: 0,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '2',
    name: 'Sony Playstation 5 Pro White ',
    image: 'images/Sony/playstation5.jpg',
    description:
      'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
    brand: 'Sony',
    category: 'Electronics',
    price: 639.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '3',
    name: 'iPhone 12 Pro "WHITE" 256GB',
    image: 'images/Apple/iphonegold.jpg',
    description:
      'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
    brand: 'Apple',
    category: 'Electronics',
    price: 999.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '4',
    name: 'Airpods Wireless Bluetooth',
    image: 'images/Apple/airpods1.jpg',
    description:
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    brand: 'Apple',
    category: 'Electronics',
    price: 39.99,
    countInStock: 0,
    rating: 2.5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'iPhone 11 Pro 256GB Memory',
    image: 'images/Apple/apple.jpg',
    description:
      'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
    brand: 'Apple',
    category: 'Electronics',
    price: 799.99,
    countInStock: 5,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '6',
    name: 'Canon EOS 2000D EF-S 18-55 III',
    image: 'images/canon/camera.jpg',
    description:
      'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
    brand: 'Cannon',
    category: 'Electronics',
    price: 499.99,
    countInStock: 5,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'Sony Playstation 4 Pro Black ',
    image: 'images/Sony/playstation.jpg',
    description:
      'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
    brand: 'Sony',
    category: 'Electronics',
    price: 299.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Logitech G-Series Gaming',
    image: 'images/mouse/mouse.jpg',
    description:
      'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
    brand: 'Logitech',
    category: 'Electronics',
    price: 29.99,
    countInStock: 5,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '9',
    name: 'Xiaomi Redmi Note 9 ',
    image: 'images/Redmi/mi11.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'Redmi',
    category: 'Electronics',
    price: 299.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '10',
    name: 'Apple watch Blue',
    image: 'images/Apple/watch3.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'Apple',
    category: 'Electronics',
    price: 255.99,
    countInStock: 3,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '11',
    name: 'Apple watch White',
    image: 'images/Apple/watch2.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'Apple',
    category: 'Electronics',
    price: 255.99,
    countInStock: 3,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '12',
    name: 'Apple watch Black',
    image: 'images/Apple/watch1.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'Apple',
    category: 'Electronics',
    price: 255.99,
    countInStock: 3,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '13',
    name: 'Apple MacBook Pro 13',
    image: 'images/Apple/mackbook.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'Apple',
    category: 'Electronics',
    price: 1299.99,
    countInStock: 3,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '14',
    name: 'Apple iPad Air 10.9',
    image: 'images/Apple/black.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'Apple',
    category: 'Electronics',
    price: 739.99,
    countInStock: 3,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '15',
    name: 'Xiaomi Redmi Note 8 Pro',
    image: 'images/Redmi/redmi1.jpg',
    description:
      'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
    brand: 'Redmi',
    category: 'Electronics',
    price: 299.99,
    countInStock: 5,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '16',
    name: 'Xiaomi Redmi Note 9 Pro',
    image: 'images/Redmi/mi11white.jpg',
    description:
      'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
    brand: 'Redmi',
    category: 'Electronics',
    price: 399.99,
    countInStock: 5,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '17',
    name: 'Samsung Galaxy S10 ',
    image: 'images/samsung/s10.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'Samsung',
    category: 'Electronics',
    price: 799.99,
    countInStock: 0,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '18',
    name: 'Sony Playstation 4 Pro  ',
    image: 'images/Sony/play.jpg',
    description:
      'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
    brand: 'Sony',
    category: 'Electronics',
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '19',
    name: 'Sony Playstation 4 Pro ',
    image: 'images/Sony/playstationRed.jpg',
    description:
      'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
    brand: 'Sony',
    category: 'Electronics',
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '20',
    name: 'Sony Playstation 3 Slim',
    image: 'images/Sony/playstation3.jpg',
    description:
      'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
    brand: 'Sony',
    category: 'Electronics',
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '21',
    name: 'Logitech G-Series black Mouse',
    image: 'images/mouse/mouse1.jpg',
    description:
      'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
    brand: 'Logitech',
    category: 'Electronics',
    price: 49.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '22',
    name: 'Samsung buds white',
    image: 'images/samsung/buds.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'Samsung',
    category: 'Electronics',
    price: 105.99,
    countInStock: 5,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '23',
    name: 'Samsung buds black',
    image: 'images/samsung/budsblack.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'Samsung',
    category: 'Electronics',
    price: 105.99,
    countInStock: 4,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '24',
    name: 'Samsung buds yellow',
    image: 'images/samsung/budsYellow.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'Samsung',
    category: 'Electronics',
    price: 105.99,
    countInStock: 0,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '25',
    name: 'Samsung Galaxy A51 128GB ',
    image: 'images/samsung/a51.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'Samsung',
    category: 'Electronics',
    price: 255.99,
    countInStock: 0,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '26',
    name: 'Samsung Galaxy S21 Ultra',
    image: 'images/samsung/s21ultra.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'Samsung',
    category: 'Electronics',
    price: 1499.99,
    countInStock: 5,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '27',
    name: 'Ноутбук HP 17-ca',
    image: 'images/laptop/lap1.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'Laptop',
    category: 'Electronics',
    price: 255.99,
    countInStock: 0,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '28',
    name: 'Ноутбук ASUS VivoBook ',
    image: 'images/laptop/lap1.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'Laptop',
    category: 'Electronics',
    price: 255.99,
    countInStock: 0,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '29',
    name: 'Samsung Galaxy S21 ',
    image: 'images/samsung/s21.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'Samsung',
    category: 'Electronics',
    price: 1299.99,
    countInStock: 5,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '30',
    name: 'Ноутбук Acer Aspire ',
    image: 'images/laptop/lap3.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'Laptop',
    category: 'Electronics',
    price: 255.99,
    countInStock: 0,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '31',
    name: 'Canon EOS 2000D EF-S 18-55 III',
    image: 'images/canon/camera1.jpg',
    description:
      'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
    brand: 'Cannon',
    category: 'Electronics',
    price: 799.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '32',
    name: 'Canon i-SENSYS MF237w',
    image: 'images/canon/printer.jpg',
    description:
      'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
    brand: 'Cannon',
    category: 'Electronics',
    price: 255.99,
    countInStock: 5,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '33',
    name: 'Logitech G-Series Gaming',
    image: 'images/mouse/mouse2.jpg',
    description:
      'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
    brand: 'Logitech',
    category: 'Electronics',
    price: 105.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
];



export default hpCharacters